on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ubuntu_runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run tests
        run: |
          echo '--- START WORK ON REMOTE SERVER ---';
          sudo apt update && sudo apt install python3
          echo '--- DOWNLOADING PYTHON ---';
          python3 -m unittest discoverd -s tests
          echo '--- START TESTS ---';
  windows_runner:
    runs-on: windows-lates
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run tests
        run: |
          echo '--- START WORK ON REMOTE SERVER ---';
          python -m pip install --upgrade pip
          echo '--- DOWNLOADING PYTHON ---';
          python3 -m unittest discoverd -s tests
          echo '--- START TESTS ---';
